//
//  ChatParametersEditScreen.swift
//  GPTExplorer
//
//  Created by James Rochabrun on 12/13/23.
//

import SwiftUI
import SwiftOpenAI

//extension ChatCompletionParameters: Equatable {
//   
//   public static func == (lhs: ChatCompletionParameters, rhs: ChatCompletionParameters) -> Bool {
//      lhs.frequencyPenalty == rhs.frequencyPenalty &&
//      lhs.logitBias == rhs.logitBias &&
//      lhs.maxTokens == rhs.maxTokens &&
//      lhs.n == rhs.n &&
//      lhs.presencePenalty == rhs.presencePenalty &&
//      lhs.responseFormat == rhs.responseFormat &&
//      lhs.seed == rhs.seed &&
//      lhs.stop == rhs.stop &&
//      lhs.temperature == rhs.temperature &&
//      lhs.topP == rhs.topP &&
//      lhs.user == rhs.user
//   }
//}

struct ChatParametersEditScreen: View {
   
   @Binding var parameters: ChatCompletionParameters
   
   enum ResponseFormat: String, CaseIterable {
      case jsonObject = "json_object"
      case text
   }
   
   var body: some View {
      NavigationView {
         ScrollView {
            VStack(alignment: .leading, spacing: Sizes.spacingExtraLarge + 10) {
               frequencyPenalty
               logitBias
               maxTokens
               n
               presencePenalty
               responseFormat
               seed
               stop
               stream
               temperature
               topP
               user
            }
            .animation(.easeInOut, value: isFrequencyPenaltyExpanded)
            .animation(.easeInOut, value: isLogitBiasExpanded)
            .animation(.easeInOut, value: isMaxTokensExpanded)
            .animation(.easeInOut, value: isNExpanded)
            .animation(.easeInOut, value: isPresencePenaltyExpanded)
            .animation(.easeInOut, value: isResponseFormatExpanded)
            .animation(.easeInOut, value: isSeedExpanded)
            .animation(.easeInOut, value: isStopExpanded)
            .animation(.easeInOut, value: isStreamExpanded)
            .animation(.easeInOut, value: isTemperatureExpanded)
            .animation(.easeInOut, value: isTopPExpanded)
            .animation(.easeInOut, value: isUserExpanded)
            .onFirstAppear {
               print("Parameters: initial parameters \(parameters)")
            }
//            .onChange(of: parameters) { oldValue, newValue in
//               print("Parameters: changed parameters \(newValue)")
//            }
            .padding()
            .tint(ThemeColor.brandColor)
         }
         .navigationTitle("Chat Parameters")
         .navigationBarTitleDisplayMode(.large)
      }
   }

   var frequencyPenalty: some View {
      InputHeaderView(
         title: "Frequency Penalty",
         subtitle: "number or null Optional Defaults to 0",
         isExpanded: $isFrequencyPenaltyExpanded)
      {
         VStack {
            Slider(value: $parameters.frequencyPenalty.orZero, in: -2.0...2.0)
            Text("\(parameters.frequencyPenalty ?? 0, specifier: "%.1f") frequencyPenalty")
         }
      } expandableContent: {
         VStack {
            Text("Number between -2.0 and 2.0. Positive values penalize new tokens based on their existing frequency in the text so far, decreasing the model's likelihood to repeat the same line verbatim. Defaults to 0")
            Text("[See more information about frequency and presence penalties.](https://platform.openai.com/docs/guides/text-generation/parameter-details)")
         }
      }
      .inputViewStyle(.card)
   }
   
   var logitBias: some View {
      InputHeaderView(
         title: "Logit Bias",
         subtitle: "map Optional Defaults to null",
         isExpanded: $isLogitBiasExpanded) {
            LogitBiasView(tokenBiasMap: $parameters.logitBias.orEmpty)
         } expandableContent: {
            Text("Modify the likelihood of specified tokens appearing in the completion. Accepts a JSON object that maps tokens (specified by their token ID in the tokenizer) to an associated bias value from -100 to 100. Mathematically, the bias is added to the logits generated by the model prior to sampling. The exact effect will vary per model, but values between -1 and 1 should decrease or increase likelihood of selection; values like -100 or 100 should result in a ban or exclusive selection of the relevant token. Defaults to null")
         }
         .inputViewStyle(.card)
   }
   
   var maxTokens: some View {
      InputHeaderView(
         title: "Max Tokens ",
         subtitle: "integer or null Optional",
         isExpanded: $isMaxTokensExpanded) {
            CustomNumericTextField(value: $apiMaxTokens, placeholder: "Max Tokens")
         } expandableContent: {
            Text("The maximum number of tokens to generate in the chat completion. The total length of input tokens and generated [tokens](https://platform.openai.com/tokenizer) is limited by the model's context length.")
         }
         .inputViewStyle(.card)
         .onChange(of: apiMaxTokens) { oldValue, newValue in
            if oldValue != newValue {
               parameters.maxTokens = newValue
            }
         }
   }
   
   var n: some View {
      InputHeaderView(
         title: "Number of choices",
         subtitle: "integer or null Optional Defaults to 1",
         isExpanded: $isNExpanded) {
            CustomNumericTextField(value: $apiNumbersOfChoice, placeholder: "Number of chat completion choices")
         } expandableContent: {
            Text("How many chat completion choices to generate for each input message. Note that you will be charged based on the number of generated tokens across all of the choices. Keep n as 1 to minimize costs. Defaults to 1")
         }
         .inputViewStyle(.card)
         .onChange(of: apiNumbersOfChoice) { oldValue, newValue in
            if oldValue != newValue {
               parameters.n = newValue
            }
         }
   }
   
   var presencePenalty: some View {
      InputHeaderView(
         title: "Presence Penalty",
         subtitle: "number or null Optional Defaults to 0",
         isExpanded: $isPresencePenaltyExpanded)
      {
         VStack {
            Slider(value: $parameters.presencePenalty.orZero, in: -2.0...2.0)
            Text("\(parameters.presencePenalty ?? 0, specifier: "%.1f") presencePenalty")
         }
      } expandableContent: {
         VStack {
            Text("Number between -2.0 and 2.0. Positive values penalize new tokens based on whether they appear in the text so far, increasing the model's likelihood to talk about new topics. Defaults to 0")
            Text("[See more information about frequency and presence penalties.](https://platform.openai.com/docs/guides/text-generation/parameter-details)")
         }
      }
      .inputViewStyle(.card)
   }
   
   var responseFormat: some View {
      InputHeaderView(
         title: "Response format",
         subtitle: "object Optional",
         isExpanded: $isResponseFormatExpanded)
      {
         Picker("Response Format", selection: $apiResponseFormat) {
            ForEach(ResponseFormat.allCases, id: \.self) { format in
               Text(format.rawValue)
                  .tag(format.rawValue as String?)
            }
         }
         .pickerStyle(SegmentedPickerStyle())
         .onChange(of: apiResponseFormat) { oldValue, newValue in
            if oldValue != newValue {
               parameters.responseFormat = .init(type: newValue.rawValue)
               print("Selected format: \(String(describing: newValue))")
            }
         }
      } expandableContent: {
         Text("An object specifying the format that the model must output. Setting to { `type`: `json_object` } enables JSON mode, which guarantees the message the model generates is valid JSON. Important: when using JSON mode, you must also instruct the model to produce JSON yourself via a system or user message. Without this, the model may generate an unending stream of whitespace until the generation reaches the token limit, resulting in a long-running and seemingly `stuck` request. Also note that the message content may be partially cut off if finish_reason=`length`, which indicates the generation exceeded max_tokens or the conversation exceeded the max context length. Defaults to text")
      }
      .inputViewStyle(.card)
   }
   
   var seed: some View {
      InputHeaderView(
         title: "Seed",
         subtitle: "integer or null Optional",
         isExpanded: $isSeedExpanded) {
            CustomNumericTextField(value: $apiSeed, placeholder: "Seed")
         } expandableContent: {
            Text("This feature is in **Beta**. If specified, our system will make a best effort to sample deterministically, such that repeated requests with the same seed and parameters should return the same result. Determinism is not guaranteed, and you should refer to the system_fingerprint response parameter to monitor changes in the backend.")
         }
         .inputViewStyle(.card)
         .onChange(of: apiSeed) { oldValue, newValue in
            if oldValue != newValue {
               parameters.seed = newValue
               print("Selected apiSeed: \(String(describing: apiSeed))")
            }
         }
   }
   
   var stop: some View {
      InputHeaderView(
         title: "Stop",
         subtitle: "string / array / null Optional Defaults to null",
         isExpanded: $isStopExpanded) {
            StopSequencesView(stopSequences: $parameters.stop)
         } expandableContent: {
            Text("Up to 4 sequences where the API will stop generating further tokens.")
         }
         .inputViewStyle(.card)
   }
   
   var stream: some View {
      InputHeaderView(
         title: "Stream",
         subtitle: "boolean or null Optional Defaults to false",
         isExpanded: $isStreamExpanded)
      {
         Toggle(isOn: $apiStream) {
            Text("Stream")
         }
         // TODO: update when package is updated to expose stream parameter
      } expandableContent: {
         Text("If set, partial message deltas will be sent, like in ChatGPT. Tokens will be sent as data-only [server-sent events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events#Event_stream_format) as they become available, with the stream terminated by a data: [DONE] message. [Example Python code.](https://cookbook.openai.com/examples/how_to_stream_completions)")
      }
      .inputViewStyle(.card)
   }
   
   var temperature: some View {
      InputHeaderView(
         title: "Temperature",
         subtitle: "number or null Optional Defaults to 1",
         isExpanded: $isTemperatureExpanded) {
            Slider(value: $parameters.temperature.orDefaultOne, in: 0...2)
            Text("\(parameters.temperature ?? 1) temperature")
         } expandableContent: {
            Text("What sampling temperature to use, between 0 and 2. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic. **We generally recommend altering this or top_p but not both.**")
         }
         .inputViewStyle(.card)
   }
   
   var topP: some View {
      InputHeaderView(
         title: "Top P",
         subtitle: "number or null Optional Defaults to 1",
         isExpanded: $isTopPExpanded) {
            VStack {
               Slider(value: $parameters.topP.orDefaultOne, in: 0...2)
               Text("\(parameters.topP ?? 1) topP")
            }
         } expandableContent: {
            Text("An alternative to sampling with temperature, called nucleus sampling, where the model considers the results of the tokens with top_p probability mass. So 0.1 means only the tokens comprising the top 10% probability mass are considered. **We generally recommend altering this or temperature but not both.**")
         }
         .inputViewStyle(.card)
   }
   
   var user: some View {
      InputHeaderView(
         title: "User",
         subtitle: "string Optional",
         isExpanded: $isUserExpanded) {
            CustomTextField(text: $parameters.user.orEmpty, placeholder: "User")
         } expandableContent: {
            Text("A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse. [Learn more](https://platform.openai.com/docs/guides/safety-best-practices/end-user-ids).")
         }
         .inputViewStyle(.card)
   }
   
   // MARK: Private
   
   @State private var apiResponseFormat: ResponseFormat = .text
   @State private var apiMaxTokens = 0
   @State private var apiSeed = 0
   @State private var apiStream = false
   @State private var apiNumbersOfChoice = 0

   @State private var isFrequencyPenaltyExpanded = false
   @State private var isLogitBiasExpanded = false
   @State private var isMaxTokensExpanded = false
   @State private var isNExpanded = false
   @State private var isPresencePenaltyExpanded = false
   @State private var isResponseFormatExpanded = false
   @State private var isSeedExpanded = false
   @State private var isStopExpanded = false
   @State private var isStreamExpanded = false
   @State private var isTemperatureExpanded = false
   @State private var isTopPExpanded = false
   @State private var isUserExpanded = false
}

#Preview {
   ChatParametersEditScreen(parameters: .constant(.init(messages: [], model: .gpt35Turbo0613)))
}

private struct LogitBiasView: View {
   @Binding var tokenBiasMap: [Int: Double]
   @State private var tokenBiasPairs: [TokenBiasPair]
   
   init(tokenBiasMap: Binding<[Int: Double]>) {
      _tokenBiasMap = tokenBiasMap
      _tokenBiasPairs = State(initialValue: tokenBiasMap.wrappedValue.map { TokenBiasPair(token: $0.key, bias: $0.value) })
   }
   
   var body: some View {
      VStack {
         ForEach($tokenBiasPairs.indices, id: \.self) { index in
            HStack {
               CustomNumericTextField(value: $tokenBiasPairs[index].token, placeholder: "Token ID")
               Slider(value: $tokenBiasPairs[index].bias, in: -100...100)
               Text("\(tokenBiasPairs[index].bias, specifier: "%.0f")")
               Button(action: { deleteTokenBiasPair(at: index) }) {
                  Image(systemName: "minus.circle")
               }
            }
         }
         Button(action: addTokenBiasPair) {
            Text("Add Token-Bias Pair")
         }
      }
      .onChange(of: tokenBiasPairs) { _,_ in
         updateTokenBiasMap()
      }
   }
   
   private func addTokenBiasPair() {
      tokenBiasPairs.append(TokenBiasPair(token: 0, bias: 0.0))
   }
   
   private func deleteTokenBiasPair(at index: Int) {
      tokenBiasPairs.remove(at: index)
      updateTokenBiasMap() // Update the tokenBiasMap after deletion
   }
   
   private func updateTokenBiasMap() {
      let groupedPairs = Dictionary(grouping: tokenBiasPairs, by: { $0.token })
      tokenBiasMap = groupedPairs.mapValues { pairs in
         // Resolve duplicates - for example, by taking the last value
         pairs.last?.bias ?? 0.0
      }
   }
}

private struct TokenBiasPair: Equatable {
   var token: Int
   var bias: Double
}

private struct StopSequencesView: View {
   
   @Binding var stopSequences: [String]?
   private let maxSequences = 4
   
   var body: some View {
      VStack {
         ForEach(0..<(stopSequences?.count ?? 0), id: \.self) { index in
            HStack {
               TextField("Stop Sequence \(index + 1)", text: Binding(
                  get: { self.stopSequences?[index] ?? "" },
                  set: { self.stopSequences?[index] = $0 }
               ))
               Button(action: { removeSequenceField(at: index) }) {
                  Image(systemName: "minus.circle")
               }
            }
         }
         
         if (stopSequences?.count ?? 0) < maxSequences {
            Button(action: addSequenceField) {
               Text("Add Stop Sequence")
            }
         }
      }
   }
   
   private func addSequenceField() {
      if stopSequences == nil {
         stopSequences = []
      }
      if (stopSequences?.count ?? 0) < maxSequences {
         stopSequences?.append("")
      }
   }
   
   private func removeSequenceField(at index: Int) {
      stopSequences?.remove(at: index)
   }
}
